#!/bin/bash
echo "=== VibeLingo Deploy Guide ==="
echo ""
echo "FRONTEND (Vercel):"
echo "1. Push code to GitHub"
echo "2. Go to vercel.com/new"
echo "3. Import your repo"
echo "4. Set environment variables:"
echo "   VITE_SUPABASE_URL=..."
echo "   VITE_SUPABASE_ANON_KEY=..."
echo "5. Deploy!"
echo ""
echo "BACKEND (Railway):"
echo "1. Go to railway.app/new"
echo "2. Deploy from GitHub"
echo "3. Set environment variables:"
echo "   STRIPE_SECRET_KEY=..."
echo "   STRIPE_WEBHOOK_SECRET=..."
echo "   TELEGRAM_BOT_TOKEN=..."
echo "   WEBAPP_URL=https://your-vercel-app.vercel.app"
echo "   SUPABASE_SERVICE_ROLE_KEY=..."
echo "   VITE_SUPABASE_URL=..."
echo "   VITE_SUPABASE_ANON_KEY=..."
echo "   PORT=3001"
echo ""
echo "SUPABASE:"
echo "1. Go to supabase.com/dashboard"
echo "2. Create new project"
echo "3. Go to SQL Editor"
echo "4. Run supabase/migrations/001_initial.sql"
echo "5. Copy URL and anon key to env vars"
echo ""
echo "STRIPE WEBHOOK:"
echo "1. Go to dashboard.stripe.com/webhooks"
echo "2. Add endpoint: https://your-railway-url.up.railway.app/api/webhook"
echo "3. Select events: checkout.session.completed, customer.subscription.updated, customer.subscription.deleted, invoice.payment_failed"
echo "4. Copy webhook secret to STRIPE_WEBHOOK_SECRET"
echo ""
echo "TELEGRAM:"
echo "1. Message @BotFather"
echo "2. /mybots -> your bot -> Bot Settings -> Menu Button"
echo "3. Set URL: https://your-vercel-app.vercel.app"
