#!/bin/bash
echo "=== Railway Setup ==="
echo ""
echo "Required environment variables:"
echo "  STRIPE_SECRET_KEY=sk_test_..."
echo "  STRIPE_WEBHOOK_SECRET=whsec_..."
echo "  TELEGRAM_BOT_TOKEN=..."
echo "  WEBAPP_URL=https://vibelingo-app.vercel.app"
echo "  VITE_SUPABASE_URL=..."
echo "  VITE_SUPABASE_ANON_KEY=..."
echo "  SUPABASE_SERVICE_ROLE_KEY=..."
echo "  PORT=3001"
echo ""
echo "Steps:"
echo "1. railway login"
echo "2. railway init"
echo "3. railway up"
echo "4. Set env vars in Railway dashboard"
echo "5. Update vercel.json with Railway URL"
